### ISSUE TITLE
Activating extension `stuart.unique-window-colors` failed:  Module did not self-register.

### ISSUE THREAD

**Issue by srenwickblum** [stuartcrobinson/unique-window-colors#23]
Firstly, I want to say I love your clever extension! We have a load of apps each of which look very similar in form, so your extension keeps me sane (well... sane-r).

Today it suddenly stopped (when I received update 1.0.49 I believe).

I tried shifting back to an older version (1.0.23) and that worked but not everywhere and using an older version doesn't seem to work terribly well in general. After reinstalling 1.0.49, it appears to work for most but not all projects. I've checked if  there is anything in .vscode that ought not to be, but it all looks ok. One project that consistently won't "colorize" has a .vscode with only a launcher.json and tasks.json - meaning, there is no settings.json there.

Version: 1.33.0 (system setup)
Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
Date: 2019-04-04T15:14:28.026Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Opening dev tools I see the following every time:

console.ts:134 [Extension Host] Activating extension `stuart.unique-window-colors` failed:  Module did not self-register.
t.log @ console.ts:134
console.ts:134 [Extension Host] Here is the error stack:  Error: Module did not self-register.
	at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
	at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
	at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:729:537)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:691:639)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:655:197)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:15:874)

**Comment by stuartcrobinson** [comment]
thank you for this!  i tried on some different windows versions and was able to reproduce this so i went ahead and reverted the published version to the version that was up last week.  

let me know if it doesn't start working as usual again for you?

**Comment by srenwickblum** [comment]
Perfect! we're back in business - thank you!

**Comment by stuartcrobinson** [comment]
ah great news! thank you for the update

**Comment by stuartcrobinson** [comment]
random question for you -- do you ever face a problem where the extension produces two different colors for different open workspaces that are confusingly similar?

**Comment by srenwickblum** [comment]
yes, there are a few cases, which surprised me (given that they are generated based on the directory path) which were strikingly similar. I also changed windowColors.Theme to light (even though I use the default Dark theme) so its easier to see the difference.
But you appear to be way ahead of the curve, I seen you provided users with a base colour and the option of providing your own colour profile. You really have done a nice job. 

Regarding the offending bug which caused the plugin to not start. If its of any help you can point me to a fix version which I can install (point me to any generic instructions I might need to install the plugin by hand) and I'll gladly test it for you on my side.
